### ISSUE TITLE
Local setup error: "The specified bucket does not exist"

### ISSUE THREAD

**Issue by Josca** [RedHatInsights/insights-ingress-go#130]
I am trying to run ingress service locally as a dependency of [yupana](https://github.com/quipucords/yupana) project. Starting it using `docker-compose up --build` it runs and seems to be ok, all services are Up after checking it using `docker-compose ps`. But:

1. After uploading archive I see the error:
`"error":"Validation topic is invalid"`. Ok, I forgot to include service name into `INGRESS_VALIDTOPICS`. However this invalid topic name is not presented in the log line, so please could you add it there?

2. After adding my service into the `INGRESS_VALIDTOPICS` env var I got another error: `"Failed to upload to minio bucket: insights-upload-perma The specified bucket does not exist"`. Even if startup job `createbuckets_1` ended with exit code 0 and logged: `Bucket created successfully myminio/insights-upload-perma.`. Strage thing is it also logged: `mc: <ERROR> Unable to initialize new config from the provided credentials. Get http://minio:9000/probe-bucket-sign-df9ughw6v54w/?location=: dial tcp 172.19.0.2:9000: connect: connection refused.` I have no idea where the problem is. **Could anybody help me with that?**

3. That's cool it's possible to start all setup locally using `docker-compose up` but for testing there is no testing archive included. Could you please provide the way how to create testing archive? Of course I can obtain testing archive somehow, but if there is some issue with uploading (like I have) it's not clear whether problem is not with archive itself. So for that case and for ease of on boarding it would be better to provide "tested testing archive".

**Comment by SteveHNH** [comment]
@Josca 
I've tried to address issue 2 and 3 for you in the latest push to master.
I've collected development docs and a docker-compose file into the ./development dir. There are better instructions there on how to get the buckets created. 
It seems like a bad idea to put the archive in the repo itself. My issue there is that it will grow the repo quite a bit. You should be able to send any tarfile to the upload service as long as it doesn't exceed 100MB and has the proper content type. With that in mind, you could create any sample file you want, or use an insights archive. I've defined instructions on how to do that in the README.md file within the development directory

I'll be working on the validation topic messaging next.

**Comment by semtexzv** [comment]
Hi @SteveHNH. Since @Josca is on PTO, I've tried to run the ingress service according to the instructions provided in the development folder, and I've encountered one issue. I'm encountering `Failed to generate presigned url: Presigned URLs cannot be generated with anonymous credentials.` when uploading an archive I had for testing purposes (Some rhel8 from iqe test cases). I think this is an issue with minio.

It seems that file is uploaded OK, only the generation of presigned URL is broken.

**Comment by SteveHNH** [comment]
@semtexzv Let me take a look at it. Thanks for reporting

**Comment by SteveHNH** [comment]
@semtexzv 
Fixed! Pull the latest master and you should get the fix. There was a typo in the $MINIO_SECRET_KEY variable in the ingress definition within local-dev-start.yml

**Comment by semtexzv** [comment]
It works, thanks. :+1:

**Comment by Josca** [comment]
1) @SteveHNH ok, after some investigation I was able to upload archive. But firstly I had to login into minio and create bucket `insights-upload-perma` manually using web UI. Is it intentional? I did not find this anywhere in the doc. Previously I remember there was a job automating this, right? Why is it removed?

2) After running ~1min kafka service stopped with error message:
~~~
kafka_1      | [2020-08-10 11:21:07,938] ERROR Error while creating ephemeral at /brokers/ids/1, node already exists and owner '72065180223209473' does not match current session '72065241903792129' (kafka.zk.KafkaZkClient$CheckedEphemeral)
kafka_1      | [2020-08-10 11:21:07,946] ERROR [KafkaServer id=1] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1      | org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
kafka_1      | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:126)
kafka_1      | 	at kafka.zk.KafkaZkClient$CheckedEphemeral.getAfterNodeExists(KafkaZkClient.scala:1819)
kafka_1      | 	at kafka.zk.KafkaZkClient$CheckedEphemeral.create(KafkaZkClient.scala:1757)
kafka_1      | 	at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1724)
kafka_1      | 	at kafka.zk.KafkaZkClient.registerBroker(KafkaZkClient.scala:95)
kafka_1      | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:294)
kafka_1      | 	at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:114)
kafka_1      | 	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)
~~~
Any idea why? Does it happen for you as well?

**Comment by tahmidefaz** [comment]
Hello! We now provide a [nice little guide](https://github.com/RedHatInsights/insights-ingress-go/blob/master/development/README.md) to set up Ingress locally, and updated a few things internally to make it easier to run our service. Please re-open if you are still running into issues.
