### ISSUE TITLE
Tower uploads fail due to new status code returned from ingress.

### ISSUE THREAD

**Issue by benthomasson** [RedHatInsights/insights-ingress-go#134]
Tower previous expected a 202 return code.  Ingress is now sending 201 codes instead.  This causes Tower to retry the uploads over and over again until the size limit is reached.   We are seeing 20 times more data than a few days ago in Automation Analytics.   

Since it will take weeks to patch all the Tower systems on customer equipment we would like a special case to send 202s for our uploads.

**Comment by benthomasson** [comment]
The best solution would be to revert 6628587a6a850870fcff7a88ddb9e753d498d1e0

**Comment by SteveHNH** [comment]
Fixed
